### ISSUE TITLE
Getting Yellow Warnings in iOS

### ISSUE THREAD

**Issue by jayfar** [yuanfux/react-native-hsv-color-picker#9]
I am getting this yellow box warning in iOS when using this component on a React Native Project (Non Expo):

"Tried to set property `onClick` on view manager of view `Expo Linear Gradient` when the view manager does not export such prop."

Seems related to this:
https://github.com/expo/expo/issues/7290
with a specific solution here:
https://github.com/expo/expo/issues/7290#issuecomment-625452092

**Comment by yuanfux** [comment]
This lib is using [expo-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) for cross platform compabilities.

If the problem is related to [expo-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) and you only build for iOS/android Platform, one solution I could give is to copy the source files from this lib to your project and replace [expo-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient) with [react-native-linear-gradient](https://github.com/react-native-community/react-native-linear-gradient#readme). Note `start` & `end` props have different type definitions in these 2 libs. You may have to modify [Line 126](https://github.com/yuanfux/react-native-hsv-color-picker/blob/master/src/SaturationValuePicker.js#L126) & [Line 127](https://github.com/yuanfux/react-native-hsv-color-picker/blob/master/src/SaturationValuePicker.js#L127).
